### ISSUE TITLE
Spinner outputs text after `stop` call

### ISSUE THREAD

**Issue by sullivan-sean** [FGRibreau/spinners#26]
I'm facing a regression in `spinners` in version 3.1.0. In my application I call `spinner.stop()` and then clear the previous line using `crossterm`:
```
spinner.stop();
execute!(std::io::stdout(), Clear(ClearType::CurrentLine), cursor::Show);
```

The line is successfully cleared, but as of version 3.1.0, the spinner will produce output even after being stopped. This behavior is new in 3.1.0 and worked as expected in 3.0.1 (no output is produced after the stop call).

**Comment by FGRibreau** [comment]
Good catch @sullivan-sean, will accept a PR with non-regression test for this 👍

**Comment by ppamorim** [comment]
This issue is happening again, any idea why?
