### ISSUE TITLE
GIF to demo all spinners

### ISSUE THREAD

**Issue by wzulfikar** [FGRibreau/spinners#35]
Hey, thanks for the library! I made a GIF to show all spinners because I want to have an easy way to see/compare which spinner to use. Hope it helps others with same need.

![spinners](https://user-images.githubusercontent.com/7823011/200083093-cf48fcab-d95c-4a59-ac66-6e167dd33e7e.gif)

**Comment by FGRibreau** [comment]
Thanks a lot @wzulfikar! I've added it to the readme :)
